# Generated by Django 3.2.23 on 2023-12-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='my_image',
            field=models.ImageField(default='upload/my image/mypass.jpg', upload_to='upload/my image'),
        ),
    ]
