# Generated by Django 3.2.23 on 2023-12-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_home_my_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='my_image',
        ),
        migrations.AddField(
            model_name='home',
            name='photo',
            field=models.ImageField(default='upload/myphotos/mine.jpg', upload_to='upload/myphotos'),
        ),
    ]
