# Generated by Django 3.2.23 on 2023-12-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_home_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
