# Generated by Django 3.2.23 on 2023-12-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='work_completed',
            field=models.IntegerField(default=0),
        ),
    ]
