# Generated by Django 3.2.23 on 2023-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_home_work_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Award_Won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='Total_Clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='Years_of_Experience',
            field=models.IntegerField(default=0),
        ),
    ]
