# Generated by Django 3.2.23 on 2023-12-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_home_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='photo',
            new_name='project_photo',
        ),
    ]
