# Generated by Django 3.2.23 on 2023-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_rename_photo_home_project_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='project_photo',
            new_name='Project_photo',
        ),
        migrations.AddField(
            model_name='home',
            name='Project_Name',
            field=models.CharField(default='project name', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='Project_Type',
            field=models.CharField(default='project type', max_length=100),
        ),
    ]
