# Generated by Django 3.2.23 on 2023-12-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20231215_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='Project_Name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='Project_Type',
        ),
        migrations.RemoveField(
            model_name='home',
            name='Project_photo',
        ),
    ]
