# Generated by Django 3.2.23 on 2023-12-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20231215_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Photo', models.ImageField(default='uploads/projects/photo.jpg', upload_to='uploads/projects')),
                ('Project_Name', models.CharField(default='project name', max_length=100)),
                ('Project_Type', models.CharField(default='project type', max_length=100)),
            ],
        ),
    ]
