# Generated by Django 3.2.23 on 2023-12-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='referees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Brief_Message', models.CharField(max_length=300)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
