# Generated by Django 3.2.23 on 2023-12-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_referees'),
    ]

    operations = [
        migrations.AddField(
            model_name='referees',
            name='Referee_Photo',
            field=models.ImageField(default='uploads/referees/pic.jpg', upload_to='uploads/referees'),
        ),
    ]
