# Generated by Django 3.2.23 on 2023-12-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='servicess',
        ),
    ]
