# Generated by Django 5.2.3 on 2025-09-12 11:23

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_rename_services_servicess'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Photo', models.ImageField(default='uploads/blogs/profile.jpg', upload_to='uploads/blogs')),
                ('Blog_Category', models.CharField(max_length=30)),
                ('blog_Title_Venue', models.CharField(max_length=100)),
                ('Blog_Description', models.CharField(max_length=100)),
                ('My_Photo', models.ImageField(default='uploads/blogs/profile.jpg', upload_to='uploads/blogs')),
                ('My_Name', models.CharField(max_length=50)),
                ('Blog_Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('Photo', models.ImageField(default='uploads/feedback/feedback.png', upload_to='uploads/feedback')),
                ('date', models.DateField(default=datetime.datetime(2025, 9, 12, 11, 23, 58, 585972, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Photo1', models.ImageField(default='uploads/portfolio/portfoli.jpg', upload_to='uploads/portfolio')),
                ('Project_Photo2', models.ImageField(default='uploads/portfolio/portfoli.jpg', upload_to='uploads/portfolio')),
                ('Project_Photo3', models.ImageField(default='uploads/portfolio/portfoli.jpg', upload_to='uploads/portfolio')),
                ('Project_Category', models.CharField(max_length=100)),
                ('Project_Client', models.CharField(max_length=100)),
                ('Project_Date', models.DateField(default=django.utils.timezone.now)),
                ('project_Url', models.URLField()),
                ('Project_Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='work_done_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Photo1', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo2', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo3', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo4', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo5', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo6', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
            ],
        ),
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(default='upload/work/work.jpg', upload_to='uploads/work')),
                ('Name', models.CharField(default='name', max_length=100)),
                ('Type_of_Work', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Date_Uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Graphic_Design_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Marketig_Services_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Network_Design_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Photography_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Web_Design_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Web_Development_Description',
            field=models.CharField(max_length=2000),
        ),
    ]
