# Generated by Django 5.2.3 on 2025-09-12 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_blogs_feedback_portfolios_work_done_details_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 11, 24, 12, 104960, tzinfo=datetime.timezone.utc)),
        ),
    ]
