# Generated by Django 5.2.3 on 2025-09-12 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 11, 34, 6, 465256, tzinfo=datetime.timezone.utc)),
        ),
    ]
