# Generated by Django 3.2.23 on 2023-12-27 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_auto_20231227_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='Name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Date',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 14, 22, 42, 181062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.TimeField(default=datetime.datetime(2023, 12, 27, 14, 22, 42, 181062, tzinfo=utc)),
        ),
    ]
