# Generated by Django 3.2.23 on 2023-12-27 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_auto_20231227_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Date',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 14, 26, 4, 29553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 14, 26, 4, 30553, tzinfo=utc)),
        ),
    ]
