# Generated by Django 3.2.23 on 2023-12-27 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_auto_20231227_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Date',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 15, 14, 18, 752425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Graphic_Design_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Marketig_Services_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Network_Design_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Photography_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Web_Design_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicess',
            name='Web_Development_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 15, 14, 18, 752425, tzinfo=utc)),
        ),
    ]
