# Generated by Django 3.2.23 on 2024-01-03 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_auto_20240103_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 16, 20, 31, 644296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='Project_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 16, 20, 31, 645293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 16, 20, 31, 645293, tzinfo=utc)),
        ),
    ]
