# Generated by Django 3.2.23 on 2024-01-08 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0027_auto_20240103_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_done_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Photo1', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo2', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo3', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo4', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo5', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
                ('Project_Photo6', models.ImageField(default='uploads/workdone/work.jpg', upload_to='uploads/workdone')),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 11, 29, 48, 616356, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='Project_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 11, 29, 48, 617356, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 11, 29, 48, 617356, tzinfo=utc)),
        ),
    ]
