# Generated by Django 3.2.23 on 2024-01-08 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0028_auto_20240108_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 16, 11, 43, 660589, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='Project_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 16, 11, 43, 661587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 16, 11, 43, 660589, tzinfo=utc)),
        ),
    ]
