# Generated by Django 3.2.23 on 2024-01-08 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0029_auto_20240108_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Photo',
            field=models.ImageField(default='uploads/feedback/feedback.jpg', upload_to='uploads/feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 17, 3, 15, 66857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 17, 3, 15, 64857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='Project_Date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 17, 3, 15, 65856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 17, 3, 15, 65856, tzinfo=utc)),
        ),
    ]
